version: '3'
services:
  teamnis_api:
    build: .
    ports:
      - "3065:3000"
    depends_on:
      - teamnis_db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=teamnis
    volumes:
      - .:/app
  teamnis_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teamnis
    ports:
      - "3366:3306"